apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
  namespace: default
data:
  #Connection database config
  my.config.db: | #Vai ter apenas um arquivo no volume com as configurações
    database: mariadb
    database_uri: mariadb://localhost:3306
  teste.field: hello
  teste2: hello2
  teste3: hello3.0
immutable: true

