apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
  namespace: default
data:
  #Connection database config
  database: mysql
  database_uri: mysql://localhost:3306

  #User interface
  font.title: Arial Bold
  background2-color: red
  theme.1: clean
  theme.2: dark
  #1theme.2: dark #Erro proposital inicia com número
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-cm-env
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom: 
    - configMapRef:
        name: my-cm
