# Converter para Base64
#echo -n 'YWRtaW4=' | base64 --decode
#echo -n 'admin' | base64
apiVersion: v1
kind: Secret
metadata: 
  name: my-secret
data: #Apenas com base64 
  user: YWRtaW4= 
  pass: TXktcGFzcy0xMjM= 
stringData:
  my-database-name: mysql
immutable: true