apiVersion: v1
kind: Endpoints
metadata:
  name: my-endpoints-service #tem q ter o mesmo no do serviço que vai utilizar
subsets:
  - addresses:
      - ip: 77.68.88.76 #IIS
      #- ip: 172.17.0.6 # Apache
      #- ip: 172.17.0.5 # Nginx
    ports: 
      - port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-endpoints-service # mesmo nome do Endpoint
spec:
  ports:
    - protocol: TCP
      port : 80
      targetPort: 80