apiVersion: v1
kind: Pod
metadata:
  name: node-red
  labels:
    type: node-red
spec: 
  containers:
    - name: node-red-1
      image: nodered/node-red
      ports:
       - containerPort: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-loadbalancer
spec :
  type: LoadBalancer
  selector:
    type: node-red
  ports: 
    - name: http-1
      port: 1880
      targetPort: 1880
      nodePort: 30001