apiVersion: apps/v1
kind: DaemonSet 
metadata: 
  name: my-daemonset
  labels: 
    app: frontend

spec:
  template:
    metadata:
      name: pod-web-webserver
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
        - name: my-container-nginx   
          image: nginx
      nodeName: minikube-m03 #Define o no. Ele mata o pod se estiver em outro lugar.

  selector:
    matchLabels:
      apps: my-app