apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-15T21:28:23Z"
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
  resourceVersion: "3405"
  uid: 88e17bf6-4333-414d-bb30-57fc6886718d
spec:
  clusterIP: 10.108.149.82
  clusterIPs:
  - 10.108.149.82
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: juptyter-pods
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
